package com.oussamabenberkane.medcom.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationAllPropertiesEquals(Notification expected, Notification actual) {
        assertNotificationAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationAllUpdatablePropertiesEquals(Notification expected, Notification actual) {
        assertNotificationUpdatableFieldsEquals(expected, actual);
        assertNotificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationAutoGeneratedPropertiesEquals(Notification expected, Notification actual) {
        assertThat(actual)
            .as("Verify Notification auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationUpdatableFieldsEquals(Notification expected, Notification actual) {
        assertThat(actual)
            .as("Verify Notification relevant properties")
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getNotificationType()).as("check notificationType").isEqualTo(expected.getNotificationType()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getEmailSent()).as("check emailSent").isEqualTo(expected.getEmailSent()))
            .satisfies(a -> assertThat(a.getEmailSentAt()).as("check emailSentAt").isEqualTo(expected.getEmailSentAt()))
            .satisfies(a -> assertThat(a.getEmailDelivered()).as("check emailDelivered").isEqualTo(expected.getEmailDelivered()))
            .satisfies(a -> assertThat(a.getEmailDeliveredAt()).as("check emailDeliveredAt").isEqualTo(expected.getEmailDeliveredAt()))
            .satisfies(a -> assertThat(a.getEmailFailed()).as("check emailFailed").isEqualTo(expected.getEmailFailed()))
            .satisfies(a -> assertThat(a.getEmailFailedAt()).as("check emailFailedAt").isEqualTo(expected.getEmailFailedAt()))
            .satisfies(a -> assertThat(a.getEmailFailureReason()).as("check emailFailureReason").isEqualTo(expected.getEmailFailureReason())
            )
            .satisfies(a -> assertThat(a.getMailjetMessageId()).as("check mailjetMessageId").isEqualTo(expected.getMailjetMessageId()))
            .satisfies(a -> assertThat(a.getReadAt()).as("check readAt").isEqualTo(expected.getReadAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationUpdatableRelationshipsEquals(Notification expected, Notification actual) {
        assertThat(actual)
            .as("Verify Notification relationships")
            .satisfies(a -> assertThat(a.getWatchlist()).as("check watchlist").isEqualTo(expected.getWatchlist()))
            .satisfies(a -> assertThat(a.getPharmacy()).as("check pharmacy").isEqualTo(expected.getPharmacy()))
            .satisfies(a -> assertThat(a.getWatchlistItem()).as("check watchlistItem").isEqualTo(expected.getWatchlistItem()));
    }
}
